name: 'iOS Localizer Test Action'
description: 'Prints a test message.'
author: 'eilonkr' # Using your GitHub username

runs:
  using: 'node16' # Or node20 if you prefer
  main: 'dist/index.js'

branding: # Optional, for the GitHub Marketplace
  icon: 'globe'
  color: 'blue' 