name: 'iOS Localizer'
description: 'iOS Localizer is a GitHub Action that automates the translation of iOS app strings using OpenAI's GPT models.'
author: 'iOS Localizer'

inputs:
  xcstrings_file_path:
    description: 'Path to the Localizable.xcstrings file.'
    required: false
    default: 'Localizable.xcstrings'
  target_languages:
    description: 'Comma-separated list of language codes to translate into (e.g., es,fr,de).'
    required: true
  github_token:
    description: 'GitHub token for creating branches and pull requests. Must have contents:write and pull-requests:write permissions.'
    required: true
  pr_branch_prefix:
    description: 'Prefix for the pull request branch name.'
    required: false
    default: 'ios-localizer-updates/'
  commit_user_name:
    description: 'Name for git commit user.'
    required: false
    default: 'github-actions[bot]'
  commit_user_email:
    description: 'Email for git commit user.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_message:
    description: 'Commit message for localization updates.'
    required: false
    default: 'i18n: Update translations by iOS Localizer Action'
  pr_title:
    description: 'Title for the pull request.'
    required: false
    default: 'iOS Localizer: Automated Localization Updates'
  pr_body:
    description: 'Body content for the pull request.'
    required: false
    default: 'Automated localization updates by the iOS Localizer Action.'
  openai_model:
    description: 'OpenAI model to use for translations.'
    required: false
    default: 'gpt-4o-mini'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'globe'
  color: 'blue' 