name: 'iOS Localizer Test Action'
description: 'Prints a test message.'
author: 'iOS Localizer'

inputs:
  run_xcode_build:
    description: 'Whether to run an Xcode build before localization to refresh xcstrings.'
    required: false
    default: 'true'
  xcode_project_path:
    description: 'Path to your Xcode project (e.g., YourApp.xcodeproj). Required if run_xcode_build is true.'
    required: false
  xcode_scheme:
    description: 'Xcode scheme to build. Required if run_xcode_build is true.'
    required: false
  xcode_configuration:
    description: 'Xcode build configuration (e.g., Debug, Release).'
    required: false
    default: 'Release'
  xcode_sdk:
    description: 'Xcode SDK to use for the build (e.g., iphoneos, iphonesimulator).'
    required: false
    default: 'iphonesimulator'
  xcstrings_file_path:
    description: 'Path to the Localizable.xcstrings file.'
    required: false
    default: 'Localizable.xcstrings'
  target_languages:
    description: 'Comma-separated list of language codes to translate into (e.g., es,fr,de).'
    required: true
  github_token:
    description: 'GitHub token for creating branches and pull requests. Must have contents:write and pull-requests:write permissions.'
    required: true
  pr_branch_prefix:
    description: 'Prefix for the pull request branch name.'
    required: false
    default: 'ios-localizer-updates/'
  commit_user_name:
    description: 'Name for git commit user.'
    required: false
    default: 'github-actions[bot]'
  commit_user_email:
    description: 'Email for git commit user.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_message:
    description: 'Commit message for localization updates.'
    required: false
    default: 'i18n: Update translations by iOS Localizer Action'
  pr_title:
    description: 'Title for the pull request.'
    required: false
    default: 'iOS Localizer: Automated Localization Updates'
  pr_body:
    description: 'Body content for the pull request.'
    required: false
    default: 'Automated localization updates by the iOS Localizer Action.'
  openai_model:
    description: 'OpenAI model to use for translations.'
    required: false
    default: 'gpt-4o-mini'

runs:
  using: 'node16' # Or node20 if you prefer
  main: 'dist/index.js'

branding: # Optional, for the GitHub Marketplace
  icon: 'globe'
  color: 'blue' 